### ISSUE TITLE
gradle produces errors for release builds

### ISSUE THREAD

**Issue by paweldziura** [lfabreges/nativescript-localize#40] opened 2018-07-13 15:51 UTC
When testing the app using `tns run android` everything works fine, including translations.

When doing `tns build android --release` [...], gradle produces errors:

```
/Users/me.user/Projects/my-project/platforms/android/app/src/main/res/values/strings.xml:26: Error: "_documentType_types_notCreatedLabel_jWbNP" is not translated in "en" (English) [MissingTranslation
  <string name="_documentType_types_notCreatedLabel_jWbNP">"Not created"</string>

```
[...]

```
/Users/me.user/Projects/my-project/platforms/android/app/src/main/res/values-en/strings.xml:22: Error: "_reasonTypes_type_notCreatedLabel_19oJ4j" is translated here but not found in default locale [ExtraTranslation]
  <string name="_reasonTypes_type_notCreatedLabel_19oJ4j">"Not created"</string>
```

```
 "tns-android": {
      "version": "4.1.3"
    }
```

`tns --version //4.1.2`

**Comment by lfabreges** [comment] 2018-07-16 18:43
I thought I fixed that, which version of the plugin are you using ?

**Comment by paweldziura** [comment] 2018-07-17 14:40
I'm using 3.0.4

**Comment by lfabreges** [comment] 2018-08-17 16:59
I'm closing this as I can't reproduce the issue.

**Closed by lfabreges** 2018-08-17 16:59 UTC
